#!name= NoAd
#!desc= 广告屏蔽
#!homepage=https://yfamily.ml
#!author= Tartarus2014
#!icon= https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Advertising.png

[URL Rewrite]
# Block Ads Start

# A
# --- (Alibaba) ---
# > Taobao - gw.alicdn.com,heic.alicdn.com
^https?:\/\/(gw|heic)\.alicdn\.com\/\w{2}s\/.+\.jpg_(9\d{2}|\d{4}) - reject
^https?:\/\/(gw|heic)\.alicdn\.com\/imgextra\/.+\d{4}-\d{4}\.jpg_(9\d{2}|\d{4}) - reject
# > Xianyu - acs.m.taobao.com
^https?:\/\/acs\.m\.taobao\.com\/gw\/mtop\.taobao\.idle\.home\.welcome\/ - reject
# > AMap - m*.amap.com
^https?:\/\/m\d\.amap\.com\/ws\/valueadded\/alimama\/splash_screen\/ - reject

# ---(Baidu)---
# > Baidu NetDisk - issuecdn.baidupcs.com
^https?:\/\/pan\.baidu\.com\/rest\/\d\.\d\/pcs\/adx - reject
^https?:\/\/pan\.baidu\.com\/act\/api\/activityentry - reject
^https?:\/\/issuecdn\.baidupcs\.com\/issue\/netdisk\/guanggao - reject
# > Baidu Tieba
^https?:\/\/c\.tieba\.baidu\.com\/c\/s\/splashSchedule - reject
^https?:\/\/c\.tieba\.baidu\.com\/c\/f\/forum\/getAdInfo - reject
^https?:\/\/c\.tieba\.baidu\.com\/\w+\/\w+\/(sync|newRnSync|mlog) - reject
^https?:\/\/((25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\.){3}(25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\/\w+\/\w+\/(sync|newRnSync|mlog) - reject
^https?:\/\/((25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\.){3}(25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\/c\/s\/splashSchedule - reject
# > Baidu Map - newclient.map.baidu.com
^https?:\/\/newclient\.map\.baidu\.com\/client\/phpui2\/\?qt=ads - reject

# > CSDN - gw.csdn.net
^https?:\/\/gw\.csdn\.net\/cms-app\/v\d+\/home_page\/open_advertisement - reject

# D
# > DouYuZhiBo - rtbapi.douyucdn.cn
^https?:\/\/rtbapi\.douyucdn\.cn\/japi\/sign\/app\/getinfo - reject

# J
# > JD - api.m.jd.com,img*.360buyimg.com
^https?:\/\/api\.m\.jd.com\/client\.action\?functionId=start - reject
^https?:\/\/api\.m\.jd.com\/client\.action\?functionId=queryMaterialAdverts - reject
^https?:\/\/(bdsp-x|dsp-x)\.jd\.com\/adx\/ - reject
^https?:\/\/img\d+\.360buyimg\.com\/jddjadvertise\/ - reject

# L
^https?:\/\/app-gateway\.leisuapi\.com\/v\d\/app\/mobile\/(banners|ads) - reject

# N
# ---(NetEase)---
# > NetEase MailMaster - appconf.mail.163.com
^https?:\/\/appconf\.mail\.163\.com\/mmad\/ - reject
# > NetEase News - c.m.163.com
^https?:\/\/c\.m\.163\.com\/nc\/gl\/ - reject
# > NetEase CloudMusic - interface*.music.163.com
^https?:\/\/((25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\.){3}(25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\/eapi\/ad\/ - reject
^https?:\/\/interface(\d)?.music.163.com\/eapi\/ad\/ - reject


# T
# > Tencent Game - ssl.kohsocialapp.qq.com
^https?:\/\/ssl\.kohsocialapp\.qq\.com:\d+\/game\/buttons - reject
^https?:\/\/qt\.qq\.com\/lua\/mengyou\/get_splash_screen_info - reject
# > Tencent Music
^https?:\/\/y\.gtimg\.cn\/music\/common\/upload\/t_splash_info\/ - reject
^https?:\/\/((25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\.){3}(25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\/music\/common\/upload\/t_splash_info\/ - reject
# > Tencent WeChat - mp.weixin.qq.com
# ^https?:\/\/mp\.weixin\.qq\.com\/mp\/(ad_|advertisement) - reject


# Z
# > Zhihu - www.zhihu.com,api.zhihu.com
^https?:\/\/api\.zhihu\.com\/commercial_api\/ - reject
^https?:\/\/api\.zhihu\.com\/fringe\/ad - reject
^https?:\/\/api\.zhihu\.com\/ad - reject
^https?:\/\/api\.zhihu\.com\/appview\/api\/v\d\/answers\/\d+\/recommendations - reject
^https?:\/\/api\.zhihu\.com\/\w+\/\d+\/comments\/featured-comment-ad - reject
^https?:\/\/www\.zhihu\.com\/api\/v\d\/answers/\d+/recommendations - reject


# Block Ads End

[MITM]
hostname = %APPEND% acs.m.taobao.com,m*.amap.com,app-gateway.leisuapi.com,issuecdn.baidupcs.com,pan.baidu.com,newclient.map.baidu.com,mime.baidu.com,yxyapi*.drcuiyutao.com,rtbapi.douyucdn.cn,mobileapi-v6.elong.com,i.ys7.com,*-release.wuta-cam.com,business.msstatic.com,imeclient.openspeech.cn,api.intsig.net,ih2.ireader.com,nnapp.cloudbae.cn:0,ib-soft.net,jxd524.github.io,api.m.jd.com,img*.360buyimg.com,api.jxedt.com,appconf.mail.163.com,c.m.163.com,client.mail.163.com,interface*.music.163.com,sp.kaola.com,support.you.163.com,p.du.163.com,app-api.niu.com,api.pinduoduo.com,*.uve.weibo.com,weibointl.api.weibo.cn,tqt.weibo.cn,4gimg.map.qq.com,r.inews.qq.com,news.ssp.qq.com,mp.weixin.qq.com,www.zhihu.com,api.zhihu.com
